version: '3.4'

name: CRUD.EF.MSSQL
services:  
  api:
    container_name: CRUD.EF.MSSQL.API
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    networks:
      - default-net

  db:
    container_name: DB
    #image: mcr.microsoft.com/mssql/server:2017-latest
    image: remote-docker-mcr.artifactory.danskenet.net/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234
      - MSSQL_PID=Developer
    networks:
      - default-net
    ports:
      - "1436:1433"
networks:
  default-net:
    driver: bridge